version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"

    schedule:
      interval: "daily"

    open-pull-requests-limit: 10

    labels:
      - "dependabot"
      - "frontend"

    commit-message:
      prefix: "deps(frontend)"

  - package-ecosystem: "github-actions"
    directory: "/"

    schedule:
      interval: "weekly"

    labels:
      - "dependabot"

    commit-message:
      prefix: "deps(ci)"
